### ISSUE TITLE
BUG : Parsing error GOroutine

### ISSUE THREAD

**Issue by Femkecl** [QuokkaStake/cosmos-validators-exporter#1]
panic: strconv.ParseInt: parsing "": invalid syntax
goroutine 37 [running]:
main.StrToInt64(...)
  /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/utils.go:29
main.(*Manager).GetAllValidators.func1({0xc000560880, 0x34}, {{0xc000fea0f0, 0x6}, {0xc000d038f0, 0x23}, {0xc000fea110, 0x7}, {0xc000fea0f9, 0x4}, ...}, ...)
  /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/manager.go:237 +0x1d4b
created by main.(*Manager).GetAllValidators
  /home/runner/work/cosmos-validators-exporter/cosmos-validators-exporter/manager.go:46 +0x450
cosmos-validators-exporter.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
cosmos-validators-exporter.service: Failed with result 'exit-code'.

Old version works without issues.

**Comment by Femkecl** [comment]
Issue is fixed here : https://github.com/freak12techno/cosmos-validators-exporter/commit/6eaf17b46e414f1c83811a880fc6299033996954
